# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm dependencies in the monorepo root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"

    # Single group for ALL npm updates to avoid merge conflicts
    # This creates one PR per week with all dependency updates combined
    # Rationale: Multiple concurrent PRs cause conflicts in package.json and pnpm-lock.yaml
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"

    # Only one PR at a time - prevents merge conflicts entirely
    open-pull-requests-limit: 1

    # Assign PRs to maintainer for review
    reviewers:
      - "RobEasthope"

    # Add labels for filtering
    labels:
      - "dependencies"
      - "automated"

    # Commit message prefix follows conventional commits
    # Single prefix since all updates are grouped together
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/London"

    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

    # Only one PR at a time
    open-pull-requests-limit: 1

    reviewers:
      - "RobEasthope"

    labels:
      - "dependencies"
      - "github-actions"

    commit-message:
      prefix: "ci"
